wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    code_path: code/lab5/training/run_experiment.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
dataset:
  desc: null
  value: IamLinesDataset
experiment_group:
  desc: null
  value: null
gpu_ind:
  desc: null
  value: 0
model:
  desc: null
  value: LineModelCtc
network:
  desc: null
  value: line_lstm_ctc
train_args:
  desc: null
  value:
    batch_size: 64
    epochs: 16
